version : "3"
services:
  config-server:
    image: config-server
    container_name: config-server
    ports:
      - 8888:8888  
    volumes:
      - /host/tmp:/tmp config-server

  service-registry:
    depends_on:
      - config-server
    image: service-registry
    container_name: service-registry
    ports: 
      - 8761:8761
      
  book-facility-db:
    depends_on:
      - config-server
    image: mongo:latest
    container_name: book-facility-db
    ports:
      - 27018:27017
#    command: ["mongod"]
  book-facility:
    depends_on:
      - config-server
      - service-registry 
      - book-facility-db
    image: book-facility
    container_name: book-facility  
    ports:
      - 8082:8080

    links:
      - config-server 
      - service-registry
      - book-facility-db
      
             